# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='id',
        ),
        migrations.RemoveField(
            model_name='host',
            name='id',
        ),
        migrations.AlterField(
            model_name='group',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='_group_groups_+', to='Inventory.Group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='isPlatform',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='variables',
            field=models.ManyToManyField(blank=True, to='Inventory.Var'),
        ),
        migrations.AlterField(
            model_name='host',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
