# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='groups',
        ),
        migrations.AddField(
            model_name='group',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='parents', to='Inventory.Group'),
        ),
    ]
