# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_auto_20170627_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Var',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.Group')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='var',
            unique_together=set([('group', 'key')]),
        ),
    ]
