# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_auto_20170625_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='group',
            name='roles',
        ),
        migrations.RemoveField(
            model_name='host',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='var',
            name='group',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
