# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_auto_20170625_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('isPlatform', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='_group_groups_+', to='Inventory.Group')),
                ('roles', models.ManyToManyField(blank=True, to='Inventory.Role')),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='groups',
            field=models.ManyToManyField(to='Inventory.Group'),
        ),
        migrations.AddField(
            model_name='var',
            name='group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Inventory.Group'),
            preserve_default=False,
        ),
    ]
