# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0006_auto_20170625_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='groups',
            field=models.ManyToManyField(null=True, to='Inventory.Group'),
        ),
    ]
