# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0008_auto_20170625_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='var',
            name='id',
        ),
        migrations.AlterField(
            model_name='var',
            name='value',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
