# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0010_auto_20170625_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='var',
            name='value',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='var',
            unique_together=set([('group', 'key')]),
        ),
    ]
