# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 22:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0011_auto_20170626_0119'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='var',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='var',
            name='group',
        ),
        migrations.DeleteModel(
            name='Var',
        ),
    ]
