# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-08-13 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='groups',
            field=models.ManyToManyField(related_name='hosts', to='Inventory.Group'),
        ),
    ]
